import webpack from 'webpack';
import path from 'path';
import TerserPlugin from 'terser-webpack-plugin';
import { VueLoaderPlugin } from 'vue-loader';

export default (env) => {
	const config = {
		entry: './src/app/app.ts',
		mode: env.BUILD_TYPE === 'release' ? 'production' : 'development',
		output: {
			path: path.resolve(path.join(env.BUILD_DIR, 'src')),
			filename: 'app.js',
			library: {
				name: 'app',
				type: 'window'
			}
		},

		performance: {
			hints: false
		},

		optimization: {
			minimize: env.BUILD_TYPE === 'release',
			minimizer: [
				// See https://webpack.js.org/plugins/terser-webpack-plugin/
				new TerserPlugin({
					terserOptions: {
						format: {
							comments: false // Used to remove license information.
						}
					},
					extractComments: false // Used to remove license information.
				})
			]
		},

		// See: https://webpack.js.org/configuration/externals/
		externalsType: 'commonjs',
		externals: {
			'node:os': 'os',
			'node:fs': 'fs',
			'node:fs/promises': 'fs/promises',
			'node:crypto': 'crypto',
			'node:util': 'util',
			'node:path': 'path',
			'node:events': 'events',
			'node:zlib': 'zlib',
			'node:assert/strict': 'assert/strict',
			'node:child_process': 'child_process',
		},

		module: {
			rules: [
				{
					test: /\.ts(x)?$/,
					exclude: /node_modules/,
					loader: 'ts-loader',
					options: {
						appendTsSuffixTo: [/\.vue$/]
					}
				},
				{
					test: /\.vue$/,
					loader: 'vue-loader'
				}
			]
		},

		resolve: {
			extensions: ['.tsx', '.ts', '.js'],
			alias: {
				// See https://www.npmjs.com/package/vue for distribution versions.
				'vue': path.resolve('./node_modules/vue/dist/vue.esm-bundler.js')
			}
		},

		plugins: [
			{
				apply: (compiler) => {
					// This plug-in removes the .LICENSE.txt files that are generated by the
					// bundler, since we handle license information in a different way.
					compiler.hooks.emit.tap('RemoveLicense', (compilation) => {
						for (let name in compilation.assets) {
							if (name.endsWith('.LICENSE.txt')) {
								delete compilation.assets[name];
							}
						}
					});
				}
			},

			new webpack.DefinePlugin({
				'__VUE_OPTIONS_API__': true, // See https://link.vuejs.org/feature-flags
				'__VUE_PROD_DEVTOOLS__': false, // See https://link.vuejs.org/feature-flags
				'process.env.NODE_ENV': env.BUILD_TYPE === 'release' ? '"production"' : '"development"'
			}),

			new VueLoaderPlugin()
		]
	};

	return config;
};